server:
  port: 8081
  servlet:
    context-path: /student-api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-db:3306/school_management_test?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: test_user
    password: test@1234

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: true
  title: 学籍管理系统API文档 - 测试环境
  description: 学籍管理系统测试环境接口文档
  version: 1.0.0
  base-package: cn.codnoy.student.controller