-- ----------------------------
-- 0、创建数据库
-- ----------------------------
-- CREATE USER 'example'@'localhost' IDENTIFIED BY 'neuq168168';
CREATE USER 'example'@'%' IDENTIFIED BY 'old111222333';

CREATE DATABASE IF NOT EXISTS neuq_examples
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

-- GRANT ALL PRIVILEGES ON neuq_examples.* TO 'example'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_examples.* TO 'example'@'%' WITH GRANT OPTION;


-- CREATE USER 'neuq_168'@'localhost' IDENTIFIED BY 'neuq168168';
CREATE USER 'neuq_168'@'%' IDENTIFIED BY 'neuq168168';

CREATE DATABASE IF NOT EXISTS neuq_team01
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team02
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team03
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team04
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team05
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team06
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team07
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team08
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team09
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team10
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team11
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS neuq_team12
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

-- GRANT ALL PRIVILEGES ON neuq_team01.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team01.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team02.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team02.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team03.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team03.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team04.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team04.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team05.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team05.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team06.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team06.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team07.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team07.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team08.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team08.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team09.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team09.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team10.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team10.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team11.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team11.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- GRANT ALL PRIVILEGES ON neuq_team12.* TO 'neuq_168'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON neuq_team12.* TO 'neuq_168'@'%' WITH GRANT OPTION;

-- ----------------------------
-- 0、删除数据库
-- ----------------------------
DROP DATABASE neuq_team01;
DROP DATABASE neuq_team02;
DROP DATABASE neuq_team03;
DROP DATABASE neuq_team04;
DROP DATABASE neuq_team05;
DROP DATABASE neuq_team06;
DROP DATABASE neuq_team07;
DROP DATABASE neuq_team08;
DROP DATABASE neuq_team09;
DROP DATABASE neuq_team10;
DROP DATABASE neuq_team11;
DROP DATABASE neuq_team12;